# Generated by Django 5.0.2 on 2024-05-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='name',
            field=models.CharField(default=23, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
