# Generated by Django 5.0.2 on 2024-05-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attestation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attestation',
            old_name='attestation_question',
            new_name='attestationQuestions',
        ),
    ]
