# Generated by Django 5.0.2 on 2024-05-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attestationquestion_name_alter_attestation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attestationquestion',
            old_name='right_values',
            new_name='rightValues',
        ),
    ]
